/*
 * Generate components/kvm_record/keymap_layouts.c from web/src/layouts.ts.
 *
 *     node tools/gen_keymap.mjs          write it
 *     node tools/gen_keymap.mjs --check  fail if it is out of date
 *
 * The console turns characters into key positions to paste text. A recording's
 * subtitles need the opposite - which character a key position typed - and the
 * answer has to be the same table, or the subtitles would show "ghbdtn" for a
 * Russian "привет". So the firmware's copy is generated from the console's, and
 * tools/test.sh checks the two have not drifted.
 */
import { execFileSync } from "node:child_process";
import { mkdtempSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join, dirname } from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const target = join(here, "..", "components", "kvm_record", "keymap_layouts.c");
const out = mkdtempSync(join(tmpdir(), "espkvm-keymap-"));
const bundle = join(out, "layouts.mjs");
try {
  execFileSync(
    join(here, "..", "web", "node_modules", ".bin", "esbuild"),
    [join(here, "..", "web", "src", "layouts.ts"), "--format=esm", `--outfile=${bundle}`,
     "--log-level=error"],
    { stdio: "inherit" },
  );
} catch {
  console.error("could not build web/src/layouts.ts - run `npm ci` in web/ first");
  process.exit(2);
}
const { LAYOUTS } = await import(pathToFileURL(bundle).href);
rmSync(out, { recursive: true, force: true });

/* Only characters that show on screen; Enter and Tab are named keys. */
const SKIP = new Set(["\n", "\r", "\t"]);

function cString(s) {
  return '"' + [...Buffer.from(s, "utf8")].map((b) =>
    b >= 0x20 && b < 0x7f && b !== 0x22 && b !== 0x5c ? String.fromCharCode(b)
      : "\\x" + b.toString(16).padStart(2, "0") + '""').join("") + '"';
}

let c = `/*
 * GENERATED by tools/gen_keymap.mjs from web/src/layouts.ts - do not edit.
 *
 * Key position -> the character it types, per target keyboard layout.
 */
#include "keymap.h"

`;
const ids = Object.keys(LAYOUTS);
for (const id of ids) {
  const rows = Object.entries(LAYOUTS[id].map)
    .filter(([ch]) => !SKIP.has(ch))
    .map(([ch, e]) => ({ ch, hid: e.hid, mod: e.mod }))
    .sort((a, b) => a.hid - b.hid || a.mod - b.mod);
  c += `static const keymap_entry_t k_${id}[] = {\n`;
  for (const r of rows) {
    c += `    {0x${r.hid.toString(16).padStart(2, "0")}, 0x${r.mod.toString(16).padStart(2, "0")}, ${cString(r.ch)}},\n`;
  }
  c += `};\n\n`;
}
c += `const keymap_layout_t keymap_layouts[] = {\n`;
for (const id of ids) {
  c += `    {"${id}", k_${id}, sizeof(k_${id}) / sizeof(k_${id}[0])},\n`;
}
c += `};\n\nconst int keymap_layout_count = ${ids.length};\n`;

if (process.argv.includes("--check")) {
  let current = "";
  try {
    current = readFileSync(target, "utf8");
  } catch {}
  if (current !== c) {
    console.log("keymap_layouts.c is out of date: run node tools/gen_keymap.mjs");
    process.exit(1);
  }
  console.log(`keymap_layouts.c matches layouts.ts (${ids.length} layouts)`);
} else {
  writeFileSync(target, c);
  console.log(`wrote ${target} (${ids.length} layouts)`);
}
